name: reactv2
description: A new Flutter project.
publish_to: 'none'
version: 1.3.0+3


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  cloud_firestore: 5.4.4 
  firebase_database: ^11.1.4
  image_picker: ^1.1.2
  cached_network_image: ^3.2.1
  path: ^1.8.3
  intl: ^0.19.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1 # Actualización a la versión 0.14.1
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
