// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh9Ax7UCqEUZGukRUnJ2aNmmoQEj-KRDk',
    appId: '1:998976113095:web:325c1d9945a1e953ec71e2',
    messagingSenderId: '998976113095',
    projectId: 'reactv2-f8956',
    authDomain: 'reactv2-f8956.firebaseapp.com',
    storageBucket: 'reactv2-f8956.appspot.com',
    measurementId: 'G-HJRPPDK585',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyzmE1GsZBDAqBfR34wTz7vvYX_CqrZXU',
    appId: '1:998976113095:android:ed3050da6f4b9673ec71e2',
    messagingSenderId: '998976113095',
    projectId: 'reactv2-f8956',
    storageBucket: 'reactv2-f8956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0hnYAAgtJQz2Xn0bEudM2TSB790C5N8w',
    appId: '1:998976113095:ios:d6bfce36275eaecbec71e2',
    messagingSenderId: '998976113095',
    projectId: 'reactv2-f8956',
    storageBucket: 'reactv2-f8956.appspot.com',
    iosBundleId: 'com.example.reactv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0hnYAAgtJQz2Xn0bEudM2TSB790C5N8w',
    appId: '1:998976113095:ios:d6bfce36275eaecbec71e2',
    messagingSenderId: '998976113095',
    projectId: 'reactv2-f8956',
    storageBucket: 'reactv2-f8956.appspot.com',
    iosBundleId: 'com.example.reactv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh9Ax7UCqEUZGukRUnJ2aNmmoQEj-KRDk',
    appId: '1:998976113095:web:70cece850a30a9e2ec71e2',
    messagingSenderId: '998976113095',
    projectId: 'reactv2-f8956',
    authDomain: 'reactv2-f8956.firebaseapp.com',
    storageBucket: 'reactv2-f8956.appspot.com',
    measurementId: 'G-KGNBMRS89S',
  );
}
